services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omstu-auth
    ports: 
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://omstu:${POSTGRES_PASSWORD}@omstu-postgres/omstu_db
      - SECRET_KEY=${SECRET_KEY}  
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
    depends_on:
      - postgres
    networks:
      - omstu-network
    restart: unless-stopped

networks:
  omstu-network:
    external: true